### ISSUE TITLE
Orca - Honeypotting in the Cloud

### ISSUE THREAD

**Issue by ramimac** [ramimac/aws-customer-security-incidents#105]
https://orca.security/resources/blog/2023-honeypotting-in-the-cloud-report/

> We saw access to our SSH honeypot within 4 minutes. There were no aempts to use the key we planted, but we saw hundreds of attempts to install malware and cryptominers on our server.

> Our S3 Buckets were accessed in one hour and the keys were used within 8 hours.

> For our Docker honeypot, we created a Docker image that builds a container with an AWS config file that contains keys, then published it in a public Docker repository and waited.. However, the Docker image was never downloaded.

> We created a public registry in Amazon’s Elastic Container Registry (ECR) with names we believed would attract the interest of attackers: After 4 months, we observed two actors downloading the images and initiating calls with our keys

> Elasticsearch: While the key stored in our Elasticsearch instance wasn’t accessed or used, the instance itself was scanned repeatedly

> This Amazon EBS backup of the VM was configured to be publicly accessible without authentication. We placed the keys in the regular .aws/credentials directory of a VM. The snapshot was not downloaded, and we saw no usage of the key configured in the image.

> The Redis server was accessed within 2.5 hours of creation, but the keys in our Redis honeypot were never used.

**Comment by christophetd** [comment]
Direct link if anyone is interested to read: https://orca.security/wp-content/uploads/2023/06/Orca-Security-2023-Honeypotting-in-the-Cloud-Report-Attacker-Tactics-and-Techniques-Revealed.pdf
