### ISSUE TITLE
Lacework case

### ISSUE THREAD

**Issue by ramimac** [ramimac/aws-customer-security-incidents#186]
https://www.lacework.com/blog/detecting-ai-resource-hijacking-with-composite-alerts

**Comment by Brucedh** [comment]
Hi Rami! It's great to see you added LLMjacking to this repo.
We at Sysdig published an article in May describing how we discovered this attack, would you mind adding it too? thanks

https://sysdig.com/blog/llmjacking-stolen-cloud-credentials-used-in-new-ai-attack/
