### ISSUE TITLE
Securitas breach

### ISSUE THREAD

**Issue by christophetd** [ramimac/aws-customer-security-incidents#2]
https://www.zdnet.com/article/unsecured-aws-server-exposed-airport-employee-records-3tb-in-data/

original source: https://www.safetydetectives.com/news/securitas-leak-report/

> In a report shared with ZDNet, SafetyDetectives said one of Securitas's AWS S3 buckets was not appropriately secured, exposing over one million files on the internet. 

> The misconfigured AWS bucket, which did not require any authentication to access, ...

**Comment by ramimac** [comment]
Thanks for logging this Christophe! 

I'm internationally leaving off exposed S3 buckets from this list. I think they are well understood, and therefore uninteresting to analyze at this juncture. 

I recommend https://www.hackmageddon.com/2022/02/21/leaky-buckets-in-2022/ if you're looking to track S3 leaks!
