### ISSUE TITLE
8220 Gang

### ISSUE THREAD

**Issue by amccarthy-figma** [ramimac/aws-customer-security-incidents#29]
https://www.sentinelone.com/blog/8220-gang-cloud-botnet-targets-misconfigured-cloud-workloads/

* consider splitting out threat intelligence reports to their own section

See also: https://twitter.com/HowellONeill/status/1579498697398059008?s=20&t=HrvmQ4bVZQoPqkK8YZFRBA

**Comment by christophetd** [comment]
Unless I'm mistaken there seems to be no cloud-specific TTPs here?
