### ISSUE TITLE
Incorrect link for DNC hack

### ISSUE THREAD

**Issue by malexmave** [ramimac/aws-customer-security-incidents#3]
The second link ("DEMOCRATIC NATIONAL COMMITTEE v. THE RUSSIAN FEDERATION") links to the same URL as the first (Code spaces). I could not determine on short notice what the correct source for the link was supposed to be, so I did not open a pull request - did you want to link the full text of the lawsuit, or is there a nicer writeup?

**Comment by ramimac** [comment]
Well spotted! It's a copy paste error - I [generally have referenced](https://speakerdeck.com/ramimac/learning-from-aws-customer-security-incidents?slide=19) the case text hosted on Politico (https://www.politico.com/f/?id=00000168-6161-de11-af7d-ef7327ea0000)

**Comment by ramimac** [comment]
Thanks for the catch, I've updated the reference.
