### ISSUE TITLE
Drizly

### ISSUE THREAD

**Issue by amccarthy-figma** [ramimac/aws-customer-security-incidents#31]
https://www.ftc.gov/news-events/news/press-releases/2022/10/ftc-takes-action-against-drizly-its-ceo-james-cory-rellas-security-failures-exposed-data-25-million

> According to the [FTC’s complaint](https://www.ftc.gov/system/files/ftc_gov/pdf/202-3185-Drizly-Complaint.pdf), Drizly and Rellas were alerted to problems with the company’s data security procedures following an earlier security incident. In 2018, a Drizly employee posted company cloud computing account login information on the software development and hosting platform GitHub. As a result of this security breakdown, hackers were able to use Drizly’s servers to mine cryptocurrency until the company changed its login information for its cloud computing account. Drizly failed to take steps to adequately address its security problems while publicly claiming to have appropriate security protections in place. Two years later, a hacker breached an employee account, got access to Drizly’s corporate GitHub login information, hacked into the company’s database, and then stole customers’ information.

**Comment by ramimac** [comment]
https://www.ftc.gov/business-guidance/blog/2022/10/data-security-forecast-drizly-100-chance-far-reaching-order-provisions 

> A key starting point is the company’s information technology infrastructure. Drizly used Amazon Relational Database Service – a third-party cloud service provided by Amazon Web Services (AWS) – to host the software that ran its e-commerce platform. That’s where the company stored a significant amount of customer data, including passwords. Although the passwords were hashed – converted into new values so they aren’t stored in plain text – Drizly used at least one obsolete method the FTC described as “cryptographically broken, and widely considered insecure.”
