### ISSUE TITLE
Collect Vendor Reports on "state of the cloud"

### ISSUE THREAD

**Issue by ramimac** [ramimac/aws-customer-security-incidents#36]
* Datadog
* Ermetic
* Orca
* Snyk
* Cyentia
* Fugue
* GCP
* Wiz

+ takeaways from each

**Comment by christophetd** [comment]
What would be the intent? Showing more the vulnerability side? Or focusing on incidents?

(if the former, Datadog is mostly N/A as we focused on vulnerabilities in cloud environments)

**Comment by ramimac** [comment]
@christophetd I think it makes sense to retain the incident focus - this is just a brain dump - I'll have to review, compile, and synthesize before anything gets into the repo

addt'l - https://library.cyentia.com/search.html?q=cloud:
* IBM cost of a data breach [takeaways](https://ermetic.com/blog/cloud/ibm-cost-of-a-data-breach-2022-highlights-for-cloud-security-professionals/)
* https://www.idsalliance.org/white-paper/2022-trends-in-securing-digital-identities/
* https://fidelissecurity.com/resource/report/2022-aws-cloud-security-report
* https://go.crowdstrike.com/protectors-of-the-cloud-combating-the-rise-in-threats-to-cloud-environments-ebook.html
* https://start.paloaltonetworks.com/unit-42-cloud-threats-securing-iam
* https://www.isc2.org/-/media/5E48A83950264AB1B265B1F073F5C9FB.ashx
* https://f.hubspotusercontent20.net/hubfs/4846674/Resources%20Content/State_of_Cloud_Security_2021.pdf
* https://cdn2.hubspot.net/hubfs/2477095/Cloud%20Risk%20Surface%20Report%202019/RR_Cloud-Report_Web_final%20(1).pdf
