### ISSUE TITLE
SSRF Bug Bounty

### ISSUE THREAD

**Issue by ramimac** [ramimac/aws-customer-security-incidents#9]
- https://sirleeroyjenkins.medium.com/bypassing-ssrf-protection-to-exfiltrate-aws-metadata-from-larksuite-bf99a3599462
- https://buer.haus/2016/04/18/esea-server-side-request-forgery-and-querying-aws-meta-data/
- https://ysx.me.uk/a-pair-of-plotly-bugs-stored-xss-and-aws-metadata-ssrf/

**Comment by christophetd** [comment]
also: https://hackerone.com/reports/1406938 (hellosign/dropbox)
